### ISSUE TITLE
Глава 11. Ведение хранилищ данных и бизнес-аналитика

### ISSUE THREAD

**Issue by eye-of-the-tiger** [prikladnayainformatica2024/projectManagement#71]
Составить тестовые вопросы к материалам главы, исходя из норматива 1-2 вопроса на страницу книги, то есть к главе на 100 страниц, должно быть примерно 150   вопросов

**Comment by George305322** [comment]
https://github.com/prikladnayainformatica2024/projectManagement/wiki/%D0%9F%D0%98-4%E2%80%903-%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87-%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9-%D0%93%D0%BB%D0%B0%D0%B2%D0%B0-11-%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B
