### ISSUE TITLE
Глава 12. Управление метаданными

### ISSUE THREAD

**Issue by eye-of-the-tiger** [prikladnayainformatica2024/projectManagement#72]
Составить тестовые вопросы к материалам главы, исходя из норматива 1-2 вопроса на страницу книги, то есть к главе на 100 страниц, должно быть примерно 150   вопросов

**Comment by MuseCat77** [comment]
https://github.com/prikladnayainformatica2024/projectManagement/wiki/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0-12.-%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8-(%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B)
